USE master;
DROP DATABASE ThiTracNghiem;
CREATE DATABASE ThiTracNghiem;
GO
USE ThiTracNghiem;
GO
CREATE TABLE DotThi(
	dotthiID VARCHAR(100) PRIMARY KEY,
	dotthiTen VARCHAR(100) NOT NULL,
	dotthiNgay DATE,
	dotthiDesc NVARCHAR(MAX)
);
GO
CREATE TABLE Adm(
	admID VARCHAR(100) PRIMARY KEY,
	admTen NVARCHAR(100) NOT NULL
);
GO
CREATE TABLE Lop (
	classID INT PRIMARY KEY IDENTITY,
	classTen VARCHAR(100) NOT NULL
);
GO
CREATE TABLE SinhVien (
	svID VARCHAR(100) PRIMARY KEY,
	svPass VARCHAR(100) NOT NULL,
	svHoTen NVARCHAR(100) NOT NULL,
	svGioiTinh INT,
	svEmail VARCHAR(100) NOT NULL,
	svSdt VARCHAR(100),
	classID INT FOREIGN KEY REFERENCES dbo.Lop(classID)
);
GO
CREATE TABLE MonHoc (
	monID INT PRIMARY KEY IDENTITY,
	monName NVARCHAR(100) NOT NULL
);
GO
CREATE TABLE CauHoi (
	cauhoiID INT PRIMARY KEY IDENTITY,
	cauhoiNoiDung NVARCHAR(MAX) NOT NULL,
	cauhoiDapAnA NVARCHAR(MAX) NOT NULL,
	cauhoiDapAnB NVARCHAR(MAX) NOT NULL,
	cauhoiDapAnC NVARCHAR(MAX) NOT NULL,
	cauhoiDapAnD NVARCHAR(MAX) NOT NULL,
	cauhoiDapAnDung VARCHAR(10) NOT NULL,
	monID INT FOREIGN KEY REFERENCES dbo.MonHoc(monID)
);
GO
CREATE TABLE DeThi (
	dethiID VARCHAR(100) PRIMARY KEY,
	dethiSoCau INT NOT NULL,
	dethiDSCauHoi VARCHAR(100) NOT NULL,
	dethiMon INT FOREIGN KEY REFERENCES dbo.MonHoc(monID),
	dotthiID VARCHAR(100) FOREIGN KEY REFERENCES dbo.DotThi(dotthiID)
);
GO
CREATE TABLE DotThiLop (
	dothilopID INT PRIMARY KEY IDENTITY,
	dotthiID VARCHAR(100) FOREIGN KEY REFERENCES dbo.DotThi(dotthiID),
	classID INT FOREIGN KEY REFERENCES dbo.Lop(classID)
);
GO
CREATE TABLE DotThiMon (
	dotthimonID INT PRIMARY KEY IDENTITY,
	dotthiID VARCHAR(100) FOREIGN KEY REFERENCES dbo.DotThi(dotthiID),
	monID INT FOREIGN KEY REFERENCES dbo.MonHoc(monID)
);
GO
CREATE TABLE DotThiDeThi (
	dotthidethiID INT PRIMARY KEY IDENTITY,
	dotthiID VARCHAR(100) FOREIGN KEY REFERENCES dbo.DotThi(dotthiID),
	dethiID VARCHAR(100) FOREIGN KEY REFERENCES dbo.DeThi(dethiID)
);
GO

CREATE TABLE Diem(
	diemID INT PRIMARY KEY IDENTITY,
	dotthiID VARCHAR(100) FOREIGN KEY REFERENCES dbo.DotThi(dotthiID),
	svID VARCHAR(100) FOREIGN KEY REFERENCES dbo.SinhVien(svID)
);
GO
CREATE TABLE DiemMon(
	diemmonID INT PRIMARY KEY IDENTITY,
	monID INT FOREIGN KEY REFERENCES dbo.MonHoc(monID),
	diemID INT FOREIGN KEY REFERENCES dbo.Diem(diemID),
	diem FLOAT NOT NULL
);
